apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factorio.fullname" . }}-secrets
  labels:
    {{- include "factorio.labels" . | nindent 4 }}
type: generic
data:
  {{- if .Values.factorio.factorioComToken }}
  token: {{ .Values.factorio.factorioComToken | b64enc }}
  username: {{ .Values.factorio.factorioComUsername | b64enc }}
  {{- end }}